title: Pelle Luminosa Body Scrub
author:
  name: Angela Fisher
  email: 'info@pelleluminosascrub.com'
metadata:
    description: 'Pelle Luminosa Body Scrub is an all-natural, sugar-based body scrub designed to both exfoliate and moisturize, making the skin look dewey and feel like butter.'

logo:
  text1: "Pelle Luminosa"
  text2: "Pelle Luminosa Body Scrub"
